name: island_slide_puzzle
description: A floating slide puzzle from the Netherlands.
version: 1.1.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.3
  fake_async: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  google_fonts: ^6.1.0
  intl: ^0.18.0
  just_audio: ^0.9.20
  platform: ^3.1.0
  rive: ^0.12.3
  shared_preferences: ^2.0.13
  url_launcher: ^6.2.1

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  msix: ^3.1.0
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
          weight: 400

msix_config:
  display_name: Island Slide Puzzle
  publisher_display_name: ReneFloor Software Development
  identity_name: 5515ReneFloorSoftwareDeve.IslandSlidePuzzle
  publisher: CN=337FF815-4DE7-4305-890E-947FA235BAF9
  store: true
  msix_version: 1.1.0.0
  logo_path: ./windows/app_icon.png
  capabilities:
