name: deploy

on:
  workflow_dispatch:
  push:
    paths:
      - "lib/**"
      - "assets/**"
      - "pubspec.yaml"
      - "pubspec.lock"
      - "web/**"
    branches:
      - master

jobs:
  build-macos:
    runs-on: macos-latest
    name: Build macOS app
    if: ${{ false }}  # disable for now
    env:
      MACOS_APP_RELEASE_PATH: build/macos/Build/Products/Release
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.0-0.2.pre
          channel: beta
          cache: true

      - name: Enable macOS
        run: flutter config --enable-macos-desktop
        working-directory: ${{env.source-directory}}

      - name: Install Dependencies
        run: flutter packages get

      - name: Build for mac
        run: |
          flutter build macos \
          --build-number $GITHUB_RUN_NUMBER

      - name: Create a dmg
        run: |
          echo "Install create-dmg"
          brew install create-dmg
          
          cd $MACOS_APP_RELEASE_PATH
          
          create-dmg \
            "slide_puzzle.dmg" \
            "slide_puzzle.app"

      - uses: actions/upload-artifact@v1
        with:
          name: macos-test-build
          path: build/macos/Build/Products/Release/slide_puzzle.dmg

  deploy:
    runs-on: ubuntu-latest
    name: deploy

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.0-0.2.pre
          channel: beta
          cache: true

      - name: Install Dependencies
        run: flutter packages get

      - name: Build for Web
        run: flutter build web

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SLIDE_PUZZLE_1A294 }}'
          channelId: live
          projectId: slide-puzzle-1a294
